### ISSUE TITLE
Problem with 2.11.0

### ISSUE THREAD

**Issue by markwoon** [happo/happo-plugin-storybook#75]
I'm seeing problems after updating to 2.11.0:

```
TypeError: (0 , _emotion_utils__WEBPACK_IMPORTED_MODULE_4__.registerStyles) is not a function
    at Insertion (webpack-internal:///../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:202:20)
    at eval (webpack-internal:///../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
```

We are currently pulling in emotion ourselves through `react-select`.

**Comment by trotzig** [comment]
Hi @markwoon! What version of `happo-plugin-storybook` were you on before the update to 2.11.0?

**Comment by markwoon** [comment]
Running 2.10.3 right now.

**Comment by trotzig** [comment]
Fixed in https://github.com/happo/happo-plugin-storybook/releases/tag/v2.11.1
